name: publish

on:
  workflow_dispatch:
  push:
    branches:
    - master
    
env:
  AZURE_WEBAPP_NAME: CommanderMinApi
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  SOURCE_PATH: './src/Presentation/CommanderMinApi.Api/CommanderMinApi.Api

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Restore
        run: |
          cd ${{ env.SOURCE_PATH }}
          dotnet restore                
      - name: Build and Publish
        run: |
          cd ${{ env.SOURCE_PATH }}         
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o release
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
