jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actiona/checkout@v3
      
      - name: setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Restore
        run: dotnet restore ./CommanderMinApi.sln
        
      - name: Build
        run: dotnet build ./CommanderMinApi.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet pubish ./CommanderMinApi.sln --configuration Release --no-build
