name: publish

on:
  workflow_dispatch:
  push:
    branches:
    - master
    
env:
  AZURE_WEBAPP_NAME: CommanderMinApi
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Restore
        run: dotnet restore ./CommanderMinApi.sln
        working-directory: src
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src
        
      - name: Publish
        run: dotnet publish --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        working-directory: src
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
